vim.pack.add({ "https://github.com/BrokenSunny/native-packer" })
require("global")
require("command")
require("autocmds")
require("keymaps")
require("native-packer").setup({
  require("plugins.download.misc.repeat"),
  require("plugins.local.undotree"),
  require("plugins.local.neo-option"),
  require("plugins.download.misc.linefuse"),
  require("plugins.local.move-line"),
  require("plugins.local.move-word"),
  require("plugins.local.neo-lsp"),
  require("plugins.download.style"),
  require("plugins.local.code-action"),
  require("plugins.local.op-register"),
  require("plugins.local.simple-translate"),
  require("plugins.local.treesitter-textobject"),
  require("plugins.download.misc.lazydev"),
  require("plugins.download.misc.zen"),
  require("plugins.download.snippet.luasnip"),
  require("plugins.download.cmp.blink-cmp"),
  require("plugins.download.misc.eye-track"),
  require("plugins.download.fzf"),
  require("plugins.download.format.conform"),
  require("plugins.download.treesitter"),
  require("plugins.download.filemanager.oil"),
  -- require("plugins.download.filemanager.neo-tree"),
  require("plugins.download.misc.tiny-inline-diagnostic"),
  require("plugins.download.misc.autopairs"),
  require("plugins.download.misc.nvim-ts-autotag"),
  require("plugins.download.misc.supermaven"),
  require("plugins.download.misc.grug-far"),
  require("plugins.download.misc.toggleterm"),
  -- require("plugins.download.misc.todo-comments"),
  require("plugins.download.git.gitsigns"),
  require("plugins.download.tmux.vim-tmux-navigator"),
  require("plugins.download.window.winshift"),
  require("plugins.download.style.lualine"),
  require("plugins.download.misc.flash"),
  require("plugins.download.misc.snacks"),
  -- require("plugins.download.misc.trouble"),
  require("plugins.download.tex"),
  require("plugins.download.markdown"),
  require("plugins.download.misc.neotest"),
  -- require("plugins.download.misc.noice"),
  require("plugins.local.buffer"),
  require("plugins.download.misc.outline"),
  require("plugins.local.bufferman"),
})
