vim.g.mapleader = ";"
require("command")
require("lazy-setup").setup({
  require("plugins.custom.repeat"),
  require("plugins.custom.parse-option"),
  require("plugins.download.snippet.luasnip"),
  require("plugins.download.cmp.blank-cmp"),
  require("plugins.download.fzf.fzf-lua"),
  require("plugins.download.format.conform"),
  require("plugins.download.lsp.tiny-inline-diagnostic"),
  require("plugins.download.treesitter.treesitter"),
  require("plugins.download.tex.vimtex"),
  require("plugins.download.markdown.markdown-preview"),
  require("plugins.download.markdown.render-markdown"),
  require("plugins.download.filemanager.neo-tree"),
  require("plugins.download.filemanager.yazi"),
  require("plugins.download.filemanager.oil-nvim"),
  require("plugins.download.code.aerial"),
  require("plugins.download.code.supermaven"),
  require("plugins.download.code.typescript-tool"),
  require("plugins.download.code.twilight"),
  require("plugins.download.tmux.vim-tmux-navigator"),
  require("plugins.download.window.winshift"),
  require("plugins.download.misc.harpoon"),
  require("plugins.download.misc.grug-far"),
  -- require("plugins.download.misc.flash"),
  require("plugins.download.misc.autopairs"),
  require("plugins.download.misc.nvim-ts-autotag"),
  require("plugins.download.misc.zen-mode"),
  require("plugins.download.misc.colorizer"),
  require("plugins.download.misc.todo-comments"),
  -- require("plugins.download.misc.hop"),
  require("plugins.download.misc.undotree"),
  -- require("plugins.download.misc.numb"),
  -- require("plugins.download.misc.nvim-possession"),
  -- require("plugins.download.misc.showkey"),
  require("plugins.download.git.gitsigns"),
  -- require("plugins.download.treesitter.nvim-treesitter-context"),
  -- require("plugins.download.telescope.telescope"),
  -- require("plugins.download.lsp.lspsaga"),
  -- require("plugins.download.misc.augment"),
  -- require("plugins.code.windsurf"),

  require("plugins.download.style.mini-statusline"),
  -- require("plugins.download.style.lualine"),
  -- require("plugins.download.style.dashboard-nvim"),
  -- require("plugins.download.style.barbar"),
  -- require{"plugins.download.style.alpha-nvim",
  -- require("plugins.download.style.theme.vague"),
  -- require("plugins.download.style.theme.material"),
  -- require("plugins.download.style.theme.moonfly"),
  -- require("plugins.download.style.theme.gruvbox"),
  -- require("plugins.download.style.theme.kanagawa"),
  -- require("plugins.download.style.theme.tokyonight"),
  -- require("plugins.download.style.theme.catppuccin"),
  -- require("plugins.download.style.theme.colorbuddy"),
  -- require("plugins.download.style.theme.everforest"),
  -- require("plugins.download.style.theme.gruvbox-material"),
  -- require("plugins.download.style.theme.melange"),
  -- require("plugins.download.style.theme.night-owl"),
  -- require("plugins.download.style.theme.nightfox"),
  -- require("plugins.download.style.theme.nord"),
  -- require("plugins.download.style.theme.nordic"),
  -- require("plugins.download.style.theme.onedarkpro"),
  -- require("plugins.download.style.theme.onenord"),
  -- require("plugins.download.style.theme.rose-pine-neovim"),
  -- require("plugins.custom.colorscheme"),
  require("plugins.custom.plain-colorscheme"),
  require("plugins.custom.lsp"),
  require("plugins.custom.magic"),
  require("plugins.custom.move-line"),
  require("plugins.custom.concat-line"),
  require("plugins.custom.break-line"),
  require("plugins.custom.file-details"),
  require("plugins.custom.window-resize"),
  require("plugins.custom.window-exchange"),
  require("plugins.custom.visual-move"),
  require("plugins.custom.simple-keymap"),
  require("plugins.custom.surround"),
  require("plugins.custom.buffer-manage"),
  require("plugins.custom.tabpage-manage"),
  require("plugins.custom.code-action"),
  require("plugins.custom.open-terminal"),
})
