-- return {
--   ["<F3>oj"] = {
--     function()
--       require("hop").hint_words({ direction = 2, hint_position = 3 })
--     end,
--     { "n", "x" },
--   },
--   ["<F3>ok"] = {
--     function()
--       require("hop").hint_words({ direction = 1, hint_position = 3 })
--     end,
--     { "n", "x" },
--   },
--   ["<space><space>o"] = {
--     function()
--       require("hop").hint_words({ hint_position = 3 })
--     end,
--     { "n", "x" },
--   },
--   ["<F3>ij"] = {
--     function()
--       require("hop").hint_words({ direction = 2, hint_position = 1 })
--     end,
--     { "n", "x" },
--   },
--   ["<F3>ik"] = {
--     function()
--       require("hop").hint_words({ direction = 1, hint_position = 1 })
--     end,
--     { "n", "x" },
--   },
--   ["<space><space>i"] = {
--     function()
--       require("hop").hint_words({ hint_position = 1 })
--     end,
--     { "n", "x" },
--   },
--   ["<F3>il"] = {
--     function()
--       require("hop").hint_words({ hint_position = 1, current_line_only = true, direction = 2 })
--     end,
--     { "n", "x" },
--   },
--   ["<F3>ih"] = {
--     function()
--       require("hop").hint_words({ hint_position = 1, current_line_only = true, direction = 1 })
--     end,
--     { "n", "x" },
--   },
--   ["<F3>ol"] = {
--     function()
--       require("hop").hint_words({ hint_position = 3, current_line_only = true, direction = 2 })
--     end,
--     { "n", "x" },
--   },
--   ["<F3>oh"] = {
--     function()
--       require("hop").hint_words({ hint_position = 3, current_line_only = true, direction = 1 })
--     end,
--     { "n", "x" },
--   },
--   ["<F3>oo"] = {
--     function()
--       require("hop").hint_words({ hint_position = 3 })
--     end,
--     { "n", "x" },
--   },
--   ["<F3>ii"] = {
--     function()
--       require("hop").hint_words({ hint_position = 1 })
--     end,
--     { "n", "x" },
--   },
--   -- ["0o"] = {
--   --   function()
--   --     require("hop").hint_words({ hint_position = 3, current_line_only = true })
--   --   end,
--   --   { "n", "x" }
--   -- },
--   -- ["0i"] = {
--   --   function()
--   --     require("hop").hint_words({ hint_position = 1, current_line_only = true })
--   --   end,
--   --   { "n", "x" }
--   -- },
--   ["00o"] = {
--     function()
--       require("hop").hint_words({ hint_position = 3 })
--     end,
--     { "n", "x" },
--   },
--   ["00i"] = {
--     function()
--       require("hop").hint_words({ hint_position = 1 })
--     end,
--     { "n", "x" },
--   },
-- }
