-- opts = function()
-- return {
--   diagnostics = {
--     underline = true,
--     update_in_insert = false,
--     virtual_text = true,
--
--     --   spacing = 4,
--     --   source = "if_many",
--     --   prefix = "●",
--     --   -- this will set set the prefix to a function that returns the diagnostics icon based on the severity
--     --   -- this only works on a recent 0.10.0 build. Will be set to "●" when not supported
--     --   -- prefix = "icons",
--     -- },
--     severity_sort = true,
--     signs = {
--       text = {
--         [vim.diagnostic.severity.ERROR] = "asdf ",
--         [vim.diagnostic.severity.WARN] = " ",
--         [vim.diagnostic.severity.HINT] = " ",
--         [vim.diagnostic.severity.INFO] = " ",
--       },
--     },
--   },
--   inlay_hints = {
--     enabled = true,
--     -- exclude = { "vue" }, -- filetypes for which you don't want to enable inlay hints
--   },
--   codelens = {
--     enabled = true,
--   },
--   servers = {
--     lua_ls = {
--       settings = {
--         Lua = {
--           diagnostics = {
--             enabled = true,
--             globals = { "vim" },
--           },
--           completion = {
--             callSnippet = "Replace",
--           },
--           codeLens = {
--             enable = true,
--           },
--           hint = {
--             enable = true,
--           },
--         },
--       },
--     }
--   }
-- }
-- end,
