local M = {
  prev_word_start = require("builtin.cmdline.word").prev_word_start,
  prev_word_end = require("builtin.cmdline.word").prev_word_end,
  next_word_start = require("builtin.cmdline.word").next_word_start,
  next_word_end = require("builtin.cmdline.word").next_word_end,
  prev_WORD_start = require("builtin.cmdline.word").prev_WORD_start,
  prev_WORD_end = require("builtin.cmdline.word").prev_WORD_end,
  next_WORD_start = require("builtin.cmdline.word").next_WORD_start,
  next_WORD_end = require("builtin.cmdline.word").next_WORD_end,
  first_non_blank_character = require("builtin.cmdline.line").first_non_blank_character,
  last_non_blank_character = require("builtin.cmdline.line").last_non_blank_character,
  middle = require("builtin.cmdline.line").middle,
  delete_to_prev_word_start = require("builtin.cmdline.word").delete_to_prev_word_start,
  delete_to_prev_word_end = require("builtin.cmdline.word").delete_to_prev_word_end,
  delete_to_next_word_start = require("builtin.cmdline.word").delete_to_next_word_start,
  delete_to_next_word_end = require("builtin.cmdline.word").delete_to_next_word_end,
  delete_to_prev_WORD_start = require("builtin.cmdline.word").delete_to_prev_WORD_start,
  delete_to_prev_WORD_end = require("builtin.cmdline.word").delete_to_prev_WORD_end,
  delete_to_next_WORD_start = require("builtin.cmdline.word").delete_to_next_WORD_start,
  delete_to_next_WORD_end = require("builtin.cmdline.word").delete_to_next_WORD_end,
  delete_cword_before = require("builtin.cmdline.word").delete_cword_before,
  delete_cword_after = require("builtin.cmdline.word").delete_cword_after,
  delete_CWORD_before = require("builtin.cmdline.word").delete_CWORD_before,
  delete_CWORD_after = require("builtin.cmdline.word").delete_CWORD_after,
  delete_to_first_non_blank_character = require("builtin.cmdline.line").delete_to_first_non_blank_character,
  delete_to_last_non_blank_character = require("builtin.cmdline.line").delete_to_last_non_blank_character,
  delete_to_first_character = require("builtin.cmdline.line").delete_to_first_character,
  delete_to_last_character = require("builtin.cmdline.line").delete_to_last_character,
}

return M
