local function surround_delete(match)
  require("surround").surround_delete(match)
  require("repeat"):set(function()
    require("surround").surround_delete(match)
  end)
end

local function surround_exchange(match)
  require("surround").surround_exchange(match)
  require("repeat"):set(function()
    require("surround").surround_exchange(match)
  end)
end

return {
  dir = vim.fn.stdpath("config") .. "/lua/custom/plugins/surround",
  name = "surround",
  keys = {
    {
      "ds)",
      function()
        surround_delete(")")
      end,
    },
    {
      "ds(",
      function()
        surround_delete("(")
      end,
    },
    {
      "ds]",
      function()
        surround_delete("]")
      end,
    },
    {
      "ds[",
      function()
        surround_delete("[")
      end,
    },
    {
      "ds{",
      function()
        surround_delete("{")
      end,
    },
    {
      "ds}",
      function()
        surround_delete("}")
      end,
    },
    {
      "ds'",
      function()
        surround_delete("'")
      end,
    },
    {
      'ds"',
      function()
        surround_delete('"')
      end,
    },
    {
      "ds<",
      function()
        surround_delete("<")
      end,
    },
    {
      "ds>",
      function()
        surround_delete(">")
      end,
    },
    {
      "cs)",
      function()
        surround_exchange(")")
      end,
    },
    {
      "cs(",
      function()
        surround_exchange("(")
      end,
    },
    {
      "cs{",
      function()
        surround_exchange("{")
      end,
    },
    {
      "cs}",
      function()
        surround_exchange("}")
      end,
    },
    {
      "cs[",
      function()
        surround_exchange("[")
      end,
    },
    {
      "cs]",
      function()
        surround_exchange("]")
      end,
    },
    {
      "cs<",
      function()
        surround_exchange("<")
      end,
    },
    {
      "cs>",
      function()
        surround_exchange(">")
      end,
    },
    {
      "cs'",
      function()
        surround_exchange("'")
      end,
    },
    {
      'cs"',
      function()
        surround_exchange('"')
      end,
    },
  },
  config = function(opt)
    require("surround").setup()
  end,
}
