return {
  name = "simple-keymap.nvim",
  priority = 1000,
  config = function()
    require("simple-keymap").setup({
      add = {
        "keymaps/",
        "keymaps/select-mode",
        "test",
      },
      del = {
        ["in"] = { "x" },
        ["d0i"] = { "n", "x", "o" },
        ["d0o"] = { "n", "x", "o" },
        ["v0i"] = { "n", "x", "o" },
        ["v0o"] = { "n", "x", "o" },
      },
    })
  end,
}

-- "buffer",
-- "cmdline",
-- "comment",
-- "copy",
-- "delete",
-- "diagnostic",
-- "expand-select",
-- "file",
-- "fold",
-- "fzf",
-- "indent",
-- "insert-line",
-- "insert-mode-operator",
-- "jump",
-- "line",
-- "location-list",
-- "lsp",
-- "macro",
-- "misc",
-- "move",
-- "move-select",
-- "paste",
-- "quickfix",
-- "quit",
-- "screen-move",
-- "scroll",
-- "search",
-- "start-insert-mode",
-- "start-select-mode",
-- "start-visual-mode",
-- "stop-insert-mode",
-- "switch-option",
-- "tabpage",
-- "tagstack",
-- "terminal",
-- "text",
-- "textobject",
-- "tmux-fixed",
-- "undo",
-- "window",
-- "word-move",
