local M = {}

local function get_groups()
  local bg = vim.o.background
  local colorgroups = {
    dark = {
      hue1 = "#af706a",
      hue2 = "#af756a",
      hue3 = "#af7b6a",
      hue4 = "#af816a",
      hue5 = "#af876a",
      hue6 = "#af8d6a",
      hue7 = "#af926a",
      hue8 = "#af986a",
      hue9 = "#af9e6a",
      hue10 = "#afa36a",
      hue11 = "#afa96a",
      hue12 = "#afaf6a",
      hue13 = "#a9af6a",
      hue14 = "#a3af6a",
      hue15 = "#9daf6a",
      hue16 = "#98af6a",
      hue17 = "#92af6a",
      hue18 = "#8caf6a",
      hue19 = "#87af6a",
      hue20 = "#81af6a",
      hue21 = "#7baf6a",
      hue22 = "#75af6a",
      hue23 = "#70af6a",
      hue24 = "#6aaf6a",
      hue25 = "#6aaf70",
      hue26 = "#6aaf75",
      hue27 = "#6aaf7b",
      hue28 = "#6aaf81",
      hue29 = "#6aaf87",
      hue30 = "#6aaf8c",
      hue31 = "#6aaf92",
      hue32 = "#6aaf98",
      hue33 = "#6aaf9d",
      hue34 = "#6aafa3",
      hue35 = "#6aafa9",
      hue36 = "#6aafaf",
      hue37 = "#6aa9af",
      hue38 = "#6aa3af",
      hue39 = "#6a9daf",
      hue40 = "#6a98af",
      hue41 = "#6a92af",
      hue42 = "#6a8caf",
      hue43 = "#6a87af",
      hue44 = "#6a81af",
      hue45 = "#6a7baf",
      hue46 = "#6a75af",
      hue47 = "#6a70af",
      hue48 = "#6a6aaf",
      hue49 = "#706aaf",
      hue50 = "#756aaf",
      hue51 = "#7b6aaf",
      hue52 = "#816aaf",
      hue53 = "#876aaf",
      hue54 = "#8c6aaf",
      hue55 = "#926aaf",
      hue56 = "#986aaf",
      hue57 = "#9d6aaf",
      hue58 = "#a36aaf",
      hue59 = "#a96aaf",
      hue60 = "#af6aaf",
      hue61 = "#af6aa9",
      hue62 = "#af6aa3",
      hue63 = "#af6a9d",
      hue64 = "#af6a98",
      hue65 = "#af6a92",
      hue66 = "#af6a8c",
      hue67 = "#af6a87",
      hue68 = "#af6a81",
      hue69 = "#af6a7b",
      hue70 = "#af6a75",
      hue71 = "#af6a70",
      hue72 = "#af6a6a",

      bg0 = "#000000",
      bg1 = "#0d0d0d",
      bg2 = "#191919",
      bg3 = "#262626",
      bg4 = "#333333",
      bg5 = "#404040",
      bg6 = "#4d4d4d",
      bg7 = "#595959",
      bg8 = "#666666",
      bg9 = "#737373",
      bg10 = "#808080",
      bg11 = "#8C8C8C",
      bg12 = "#999999",
      bg13 = "#A6A6A6",
      bg14 = "#B3B3B3",
      bg15 = "#BFBFBF",
      bg16 = "#CCCCCC",
      bg17 = "#D9D9D9",
      bg18 = "#E6E6E6",
      bg19 = "#F2F2F2",
      bg20 = "#FFFFFF",
    },
    light = {},
  }
  local colors = colorgroups[bg]
  local groups = {
    dark = {
      Normal = { fg = colors.bg11, bg = colors.bg2 },
      NormalFloat = { link = "Normal" },
      NormalNC = { fg = "", bg = "" },
      CursorLine = { bg = colors.bg3 },
      CursorLineNr = { fg = colors.bg11, bold = true },
      ColorColumn = { bg = colors.bg3 },
      LineNr = { fg = colors.bg6 },
      Search = { reverse = true },
      IncSearch = { link = "Search" },
      CurSearch = { link = "IncSearch" },
      Special = { fg = colors.hue72 },
      Visual = { bg = colors.bg4 },
      VisualNOS = { link = "Visual" },
      MatchParen = { reverse = true },
      Title = { fg = colors.hue45 },
      ModeMsg = { link = "Normal", bold = true },

      TabLineFill = { bg = colors.bg1 }, -- 标签栏
      TabLine = { link = "TabLineFill" }, -- 非当前标签
      TabLineSel = { fg = colors.hue44, bg = colors.bg2, bold = true }, -- 当前标签选中

      Error = { fg = colors.hue72 },
      ErrorMsg = { fg = colors.bg2, bg = colors.hue72 },

      Added = { fg = colors.hue36 },
      Removed = { fg = colors.hue72 },

      Constant = { fg = colors.hue1 },
      Function = { fg = colors.hue46 },
      Keyword = { fg = colors.hue52 },
      Boolean = { fg = colors.hue72 },
      Number = { fg = colors.hue72 },
      String = { fg = colors.hue20 },
      Comment = { fg = colors.bg7 },
      Operator = { fg = colors.hue72 },
      Delimiter = { fg = colors.bg12 },
      Type = { fg = colors.hue30 },
      Structure = { fg = colors.hue72 },
      Folded = { bg = colors.bg3, fg = colors.hue36 },

      cString = { link = "String" },
      cType = { fg = colors.hue52 },
      cTypedef = { fg = colors.hue35 },
      cStructure = { link = "Structure" },
      ["@lsp.type.class.c"] = { link = "cType" },
      cRepeat = { fg = colors.hue72 },
      cConditional = { fg = colors.hue72 },
      cStatement = { fg = colors.hue72 },
      cInclude = { fg = colors.hue72 },

      ["@function"] = { link = "Function" },
      ["@function.call"] = { link = "Function" },
      ["@function.builtin"] = { link = "Function" },
      ["@variable"] = { fg = colors.bg11 },
      ["@variable.member"] = { fg = colors.hue48 },
      ["@variable.builtin"] = { fg = colors.hue72, bold = false },
      ["@variable.parameter"] = { fg = colors.hue7 },
      ["@module.builtin"] = { link = "@variable.builtin" },
      ["@property"] = { fg = colors.hue48 },
      ["@constructor"] = { fg = colors.bg12 },
      ["@constant"] = { link = "Constant" },
      ["@constant.builtin"] = { link = "Constant" },

      ["@lsp.type.variable"] = {},

      ["@tag"] = { fg = colors.hue72, bold = true },
      ["@tag.attribute"] = { fg = colors.hue48 },
      ["@tag.delimiter"] = { link = "Delimiter" },
      ["@tag.builtin"] = { fg = colors.hue72, bold = false },

      Label = { fg = colors.hue50, bold = true },
      ["@label"] = { link = "Label" },
      ["@label.vimdoc"] = { link = "Label" },
      ["@markup.link"] = { fg = colors.hue62 },
      ["@markup.link.label"] = { link = "@markup.link" },
      ["@markup.link.vimdoc"] = { link = "@markup.link" },

      BlinkCmpLabelDeprecated = { strikethrough = true },
      BlinkCmpKind = { fg = colors.hue52 },
      -- BlinkCmpLabel = { bg = "" },
      BlinkCmpLabelMatch = { fg = colors.hue52, bold = true },
      BlinkCmpMenuSelection = { bg = colors.bg4 },
      BlinkCmpMenu = { bg = colors.bg3 },
      BlinkCmpSource = { fg = colors.bg5 },
      BlinkCmpDoc = { bg = colors.bg3 },
      -- BlinkCmpLabelDetail = { bg = colors.bg2 },
      BlinkCmpLabelDescription = { bg = colors.bg2 },
      BlinkCmpKindText = { fg = colors.hue23 },
      BlinkCmpKindVariable = { fg = colors.hue48 },
      -- BlinkCmpKindMethod = { link = "BlinkCmpKindFunction" },
      -- BlinkCmpKindFunction = { fg = colors.purple1 },
      -- BlinkCmpKindConstructor = { link = "Gruvboxorange2" },
      -- BlinkCmpKindUnit = { link = "GruvboxBlue" },
      -- BlinkCmpKindField = { link = "GruvboxBlue" },
      -- BlinkCmpKindClass = { link = "Gruvboxorange2" },
      -- BlinkCmpKindInterface = { link = "Gruvboxorange2" },
      -- BlinkCmpKindModule = { link = "GruvboxBlue" },
      -- BlinkCmpKindProperty = { link = "GruvboxBlue" },
      -- BlinkCmpKindValue = { link = "GruvboxOrange" },
      -- BlinkCmpKindEnum = { link = "Gruvboxorange2" },
      -- BlinkCmpKindOperator = { link = "Gruvboxorange2" },
      -- BlinkCmpKindKeyword = { link = "Gruvboxblue4" },
      -- BlinkCmpKindEvent = { link = "Gruvboxblue4" },
      -- BlinkCmpKindReference = { link = "Gruvboxblue4" },
      -- BlinkCmpKindColor = { link = "Gruvboxblue4" },
      -- BlinkCmpKindSnippet = { link = "Gruvboxgreen4" },
      -- BlinkCmpKindFile = { link = "GruvboxBlue" },
      -- BlinkCmpKindFolder = { link = "GruvboxBlue" },
      -- BlinkCmpKindEnumMember = { link = "GruvboxAqua" },
      -- BlinkCmpKindConstant = { link = "GruvboxOrange" },
      -- BlinkCmpKindStruct = { link = "Gruvboxorange2" },
      -- BlinkCmpKindTypeParameter = { link = "Gruvboxorange2" },
      -- BlinkCmpGhostText = { link = "GruvboxBg4" },

      Directory = { fg = colors.hue45, bold = false },
      NeoTreeDirectoryName = { link = "Directory" },
      NeoTreeGitUntracked = { fg = colors.hue5, bold = false },
      NeoTreeGitModified = { fg = colors.hue36, bold = false },
      -- NeoTreeDotfile = { fg = colors.fg4 },
      -- NeoTreeFadeText1 = { fg = colors.fg3 },
      -- NeoTreeFadeText2 = { fg = colors.fg4 },
      -- NeoTreeFileIcon = { fg = colors.blue },
      -- NeoTreeFileName = { fg = colors.fg1 },
      -- NeoTreeFileNameOpened = { fg = colors.fg1, bold = true },
      -- NeoTreeFileStats = { fg = colors.fg3 },
      -- NeoTreeFileStatsHeader = { fg = colors.fg2, italic = true },
      -- NeoTreeFilterTerm = { link = "SpecialChar" },
      -- NeoTreeHiddenByName = { link = "NeoTreeDotfile" },
      -- NeoTreeIndentMarker = { fg = colors.fg4 },
      -- NeoTreeMessage = { fg = colors.fg3, italic = true },
      -- NeoTreeModified = { fg = colors. },
      -- NeoTreeRootName = { fg = colors.fg1, bold = true, italic = true },
      -- NeoTreeSymbolicLinkTarget = { link = "NeoTreeFileName" },
      -- NeoTreeExpander = { fg = colors.fg4 },
      -- NeoTreeWindowsHidden = { link = "NeoTreeDotfile" },
      -- NeoTreePreview = { link = "Search" },
      -- NeoTreeGitAdded = { link = "GitGutterAdd" },
      -- NeoTreeGitConflict = { fg = colors., bold = true, italic = true },
      -- NeoTreeGitDeleted = { link = "GitGutterDelete" },
      -- NeoTreeGitIgnored = { link = "NeoTreeDotfile" },
      -- NeoTreeGitRenamed = { link = "NeoTreeGitModified" },
      -- NeoTreeGitStaged = { link = "NeoTreeGitAdded" },
      -- NeoTreeGitUnstaged = { link = "NeoTreeGitConflict" },
      -- NeoTreeTabActive = { fg = colors.fg1, bold = true },
      -- NeoTreeTabInactive = { fg = colors.fg4, bg = colors.bg5 },
      -- NeoTreeTabSeparatorActive = { fg = colors.bg5 },
      -- NeoTreeTabSeparatorInactive = { fg = colors.bg2, bg = colors.bg5 },

      MiniStatuslineModeNormal = { fg = colors.bg2, bg = colors.hue46 },
      MiniStatuslineModeInsert = { fg = colors.bg2, bg = colors.hue60 },
      MiniStatuslineModeVisual = { fg = colors.bg2, bg = colors.hue30 },
      MiniStatuslineModeReplace = { fg = colors.bg2, bg = colors.hue72 },
      MiniStatuslineModeCommand = { fg = colors.bg2, bg = colors.hue25 },
      MiniStatuslineDevinfo = { fg = colors.bg11, bg = colors.bg3 },
      MiniStatuslineFilename = { fg = colors.bg2, bg = colors.bg10 },
      MiniStatuslineFileinfo = { fg = colors.bg11, bg = colors.bg3 },
      -- MiniStatuslineModeNormal = { fg = colors.bg2, bg = colors.hue46 },
      -- MiniStatuslineModeInsert = { fg = colors.bg2, bg = colors.hue60 },
      -- MiniStatuslineModeVisual = { fg = colors.bg2, bg = colors.hue30 },
      -- MiniStatuslineModeReplace = { fg = colors.bg2, bg = colors.hue72 },
      -- MiniStatuslineModeCommand = { fg = colors.bg2, bg = colors.hue25 },
      -- MiniStatuslineDevinfo = { fg = colors.bg2, bg = colors.hue17 },
      -- MiniStatuslineFilename = { fg = colors.bg2, bg = colors.hue1 },
      -- MiniStatuslineFileinfo = { fg = colors.bg11, bg = colors.bg3 },
      -- * `MiniStatuslineModeNormal` - Normal mode.
      -- * `MiniStatuslineModeInsert` - Insert mode.
      -- * `MiniStatuslineModeVisual` - Visual mode.
      -- * `MiniStatuslineModeReplace` - Replace mode.
      -- * `MiniStatuslineModeCommand` - Command mode.
      -- * `MiniStatuslineModeOther` - other modes (like Terminal, etc.).
      -- * `MiniStatuslineDevinfo` - for "dev info" group
      -- * `MiniStatuslineFilename` - for |MiniStatusline.section_filename| section.
      -- * `MiniStatuslineFileinfo` - for |MiniStatusline.section_fileinfo| section.
      -- * `MiniStatuslineInactive` - highliting in not focused window.
    },
    light = {},
  }
  return groups[bg]
end

function M.loader()
  vim.cmd("highlight clear")
  vim.o.termguicolors = true
  local groups = get_groups()
  for group, colors in pairs(groups) do
    vim.api.nvim_set_hl(0, group, colors)
  end
end

function M.setup() end

return M
