-- --- @class my.profile.promax._runtime
-- local M = {}
--
-- local cleans = {}
--
-- local function init_options()
--   vim.o.guicursor =
--     "n-v-c-sm:ver25,i-ci-ve:ver25-InsertModeCursor,r-cr-o:ver25-InsertModeCursor,t:block-blinkon500-blinkoff500-TermCursor"
--   vim.o.selection = "exclusive"
--   vim.api.nvim_set_hl(0, "InsertModeCursor", { fg = "#ffffff", bg = "#ffffff" })
--   vim.o.virtualedit = "onemore"
--   ---@diagnostic disable-next-line: param-type-mismatch
--   if not vim.list_contains(vim.opt.virtualedit:get() or {}, "onemore") then
--     ---@diagnostic disable-next-line: param-type-mismatch
--     vim.opt.virtualedit:append("onemore")
--   end
-- end
--
-- --- @param keymaps my.profile.promax.Opts.Keymap
-- local function init_keymaps(keymaps)
--   for lhs, value in pairs(keymaps) do
--     if lhs == "preset" then
--     elseif type(value) == "table" then
--       for mode, cb in pairs(value) do
--         if vim.list_contains({ "n", "i", "x", "o", "t", "c", "s", "v" }, mode) then
--           vim.keymap.set(mode, lhs, cb)
--         end
--       end
--     end
--   end
-- end
--
-- function M.init()
--   local config = my.profile.promax._config._config
--   init_options()
--   init_keymaps(config.keymap)
-- end
--
-- function M.cleanup()
--   for _, clean in ipairs(cleans) do
--     clean()
--   end
--   cleans = {}
-- end
--
-- return M
